config/routes.rb
Bliga::Application.routes.draw do
  
  root :to => 'tipps#index'
  
  resources :tipps

  resources :paarungs

  resources :spieltags

  resources :regels

  resources :saisons

  resources :ligas

  resources :vereins
  
  resources :users, :user_sessions
  
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  

end

app/models/verein.rb
class Verein < ActiveRecord::Base
	has_many :paarung
end

app/controllers/vereins_controller.rb
class VereinsController < ApplicationController
  # GET /vereins
  # GET /vereins.xml
  def index
    @vereins = Verein.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @vereins }
    end
  end

  # GET /vereins/1
  # GET /vereins/1.xml
  def show
    @verein = Verein.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @verein }
    end
  end

  # GET /vereins/new
  # GET /vereins/new.xml
  def new
    @verein = Verein.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @verein }
    end
  end

  # GET /vereins/1/edit
  def edit
    @verein = Verein.find(params[:id])
  end

  # POST /vereins
  # POST /vereins.xml
  def create
    @verein = Verein.new(params[:verein])

    respond_to do |format|
      if @verein.save
        format.html { redirect_to(@verein, :notice => 'Verein was successfully created.') }
        format.xml  { render :xml => @verein, :status => :created, :location => @verein }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @verein.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /vereins/1
  # PUT /vereins/1.xml
  def update
    @verein = Verein.find(params[:id])

    respond_to do |format|
      if @verein.update_attributes(params[:verein])
        format.html { redirect_to(@verein, :notice => 'Verein was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @verein.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /vereins/1
  # DELETE /vereins/1.xml
  def destroy
    @verein = Verein.find(params[:id])
    @verein.destroy

    respond_to do |format|
      format.html { redirect_to(vereins_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/vereins_helper.rb
module VereinsHelper
end

app/views/vereins/_form.html.erb
<%= form_for(@verein) do |f| %>
  <% if @verein.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@verein.errors.count, "error") %> prohibited this verein from being saved:</h2>

      <ul>
      <% @verein.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :logo %><br />
    <%= f.text_field :logo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vereins/edit.html.erb
<h1>Editing verein</h1>

<%= render 'form' %>

<%= link_to 'Show', @verein %> |
<%= link_to 'Back', vereins_path %>

app/views/vereins/index.html.erb
<h1>Listing vereins</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Logo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @vereins.each do |verein| %>
  <tr>
    <td><%= verein.name %></td>
    <td><%= verein.logo %></td>
    <td><%= link_to 'Show', verein %></td>
    <td><%= link_to 'Edit', edit_verein_path(verein) %></td>
    <td><%= link_to 'Destroy', verein, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Verein', new_verein_path %>

app/views/vereins/new.html.erb
<h1>New verein</h1>

<%= render 'form' %>

<%= link_to 'Back', vereins_path %>

app/views/vereins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @verein.name %>
</p>

<p>
  <b>Logo:</b>
  <%= @verein.logo %>
</p>


<%= link_to 'Edit', edit_verein_path(@verein) %> |
<%= link_to 'Back', vereins_path %>