config/routes.rb
Bliga::Application.routes.draw do
  
  root :to => 'tipps#index'
  
  resources :tipps

  resources :paarungs

  resources :spieltags

  resources :regels

  resources :saisons

  resources :ligas

  resources :vereins
  
  resources :users, :user_sessions
  
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  

end

app/models/liga.rb
class Liga < ActiveRecord::Base
	has_many :saison
end

app/controllers/ligas_controller.rb
class LigasController < ApplicationController
  # GET /ligas
  # GET /ligas.xml
  def index
    @ligas = Liga.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @ligas }
    end
  end

  # GET /ligas/1
  # GET /ligas/1.xml
  def show
    @liga = Liga.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @liga }
    end
  end

  # GET /ligas/new
  # GET /ligas/new.xml
  def new
    @liga = Liga.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @liga }
    end
  end

  # GET /ligas/1/edit
  def edit
    @liga = Liga.find(params[:id])
  end

  # POST /ligas
  # POST /ligas.xml
  def create
    @liga = Liga.new(params[:liga])

    respond_to do |format|
      if @liga.save
        format.html { redirect_to(@liga, :notice => 'Liga was successfully created.') }
        format.xml  { render :xml => @liga, :status => :created, :location => @liga }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @liga.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /ligas/1
  # PUT /ligas/1.xml
  def update
    @liga = Liga.find(params[:id])

    respond_to do |format|
      if @liga.update_attributes(params[:liga])
        format.html { redirect_to(@liga, :notice => 'Liga was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @liga.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /ligas/1
  # DELETE /ligas/1.xml
  def destroy
    @liga = Liga.find(params[:id])
    @liga.destroy

    respond_to do |format|
      format.html { redirect_to(ligas_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/ligas_helper.rb
module LigasHelper
end

app/views/ligas/_form.html.erb
<%= form_for(@liga) do |f| %>
  <% if @liga.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@liga.errors.count, "error") %> prohibited this liga from being saved:</h2>

      <ul>
      <% @liga.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ligas/edit.html.erb
<h1>Editing liga</h1>

<%= render 'form' %>

<%= link_to 'Show', @liga %> |
<%= link_to 'Back', ligas_path %>

app/views/ligas/index.html.erb
<h1>Listing ligas</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ligas.each do |liga| %>
  <tr>
    <td><%= liga.name %></td>
    <td><%= link_to 'Show', liga %></td>
    <td><%= link_to 'Edit', edit_liga_path(liga) %></td>
    <td><%= link_to 'Destroy', liga, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Liga', new_liga_path %>

app/views/ligas/new.html.erb
<h1>New liga</h1>

<%= render 'form' %>

<%= link_to 'Back', ligas_path %>

app/views/ligas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @liga.name %>
</p>


<%= link_to 'Edit', edit_liga_path(@liga) %> |
<%= link_to 'Back', ligas_path %>