config/routes.rb
Bliga::Application.routes.draw do
  
  root :to => 'tipps#index'
  
  resources :tipps

  resources :paarungs

  resources :spieltags

  resources :regels

  resources :saisons

  resources :ligas

  resources :vereins
  
  resources :users, :user_sessions
  
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  

end

app/models/paarung.rb
class Paarung < ActiveRecord::Base
	belongs_to :spieltag
	belongs_to :verein, :foreign_key => 'heim'
	belongs_to :verein, :foreign_key => 'gast'
	
	has_many :tipp
end

app/controllers/paarungs_controller.rb
class PaarungsController < ApplicationController
  # GET /paarungs
  # GET /paarungs.xml
  def index
    @paarungs = Paarung.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @paarungs }
    end
  end

  # GET /paarungs/1
  # GET /paarungs/1.xml
  def show
    @paarung = Paarung.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @paarung }
    end
  end

  # GET /paarungs/new
  # GET /paarungs/new.xml
  def new
    @paarung = Paarung.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @paarung }
    end
  end

  # GET /paarungs/1/edit
  def edit
    @paarung = Paarung.find(params[:id])
  end

  # POST /paarungs
  # POST /paarungs.xml
  def create
    @paarung = Paarung.new(params[:paarung])

    respond_to do |format|
      if @paarung.save
        format.html { redirect_to(@paarung, :notice => 'Paarung was successfully created.') }
        format.xml  { render :xml => @paarung, :status => :created, :location => @paarung }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @paarung.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /paarungs/1
  # PUT /paarungs/1.xml
  def update
    @paarung = Paarung.find(params[:id])

    respond_to do |format|
      if @paarung.update_attributes(params[:paarung])
        format.html { redirect_to(@paarung, :notice => 'Paarung was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @paarung.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /paarungs/1
  # DELETE /paarungs/1.xml
  def destroy
    @paarung = Paarung.find(params[:id])
    @paarung.destroy

    respond_to do |format|
      format.html { redirect_to(paarungs_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/paarungs_helper.rb
module PaarungsHelper
end

app/views/paarungs/_form.html.erb
<%= form_for(@paarung) do |f| %>
  <% if @paarung.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@paarung.errors.count, "error") %> prohibited this paarung from being saved:</h2>

      <ul>
      <% @paarung.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :spieltag_id %><br />
    <%= f.text_field :spieltag_id %>
  </div>
  <div class="field">
    <%= f.label :heim %><br />
    <%= f.text_field :heim %>
  </div>
  <div class="field">
    <%= f.label :gast %><br />
    <%= f.text_field :gast %>
  </div>
  <div class="field">
    <%= f.label :start %><br />
    <%= f.datetime_select :start %>
  </div>
  <div class="field">
    <%= f.label :torh %><br />
    <%= f.text_field :torh %>
  </div>
  <div class="field">
    <%= f.label :torg %><br />
    <%= f.text_field :torg %>
  </div>
  <div class="field">
    <%= f.label :verlaengerung %><br />
    <%= f.check_box :verlaengerung %>
  </div>
  <div class="field">
    <%= f.label :elfmeter %><br />
    <%= f.check_box :elfmeter %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/paarungs/edit.html.erb
<h1>Editing paarung</h1>

<%= render 'form' %>

<%= link_to 'Show', @paarung %> |
<%= link_to 'Back', paarungs_path %>

app/views/paarungs/index.html.erb
<h1>Listing paarungs</h1>

<table>
  <tr>
    <th>Spieltag</th>
    <th>Heim</th>
    <th>Gast</th>
    <th>Start</th>
    <th>Torh</th>
    <th>Torg</th>
    <th>Verlaengerung</th>
    <th>Elfmeter</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @paarungs.each do |paarung| %>
  <tr>
    <td><%= paarung.spieltag_id %></td>
    <td><%= paarung.heim %></td>
    <td><%= paarung.gast %></td>
    <td><%= paarung.start %></td>
    <td><%= paarung.torh %></td>
    <td><%= paarung.torg %></td>
    <td><%= paarung.verlaengerung %></td>
    <td><%= paarung.elfmeter %></td>
    <td><%= link_to 'Show', paarung %></td>
    <td><%= link_to 'Edit', edit_paarung_path(paarung) %></td>
    <td><%= link_to 'Destroy', paarung, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Paarung', new_paarung_path %>

app/views/paarungs/new.html.erb
<h1>New paarung</h1>

<%= render 'form' %>

<%= link_to 'Back', paarungs_path %>

app/views/paarungs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Spieltag:</b>
  <%= @paarung.spieltag_id %>
</p>

<p>
  <b>Heim:</b>
  <%= @paarung.heim %>
</p>

<p>
  <b>Gast:</b>
  <%= @paarung.gast %>
</p>

<p>
  <b>Start:</b>
  <%= @paarung.start %>
</p>

<p>
  <b>Torh:</b>
  <%= @paarung.torh %>
</p>

<p>
  <b>Torg:</b>
  <%= @paarung.torg %>
</p>

<p>
  <b>Verlaengerung:</b>
  <%= @paarung.verlaengerung %>
</p>

<p>
  <b>Elfmeter:</b>
  <%= @paarung.elfmeter %>
</p>


<%= link_to 'Edit', edit_paarung_path(@paarung) %> |
<%= link_to 'Back', paarungs_path %>